apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: Meta-Llama-3-2-1B-Instruct
spec:
  predictor:
    containers:
      - name: kserve-container
        image: docker.io/library/meta-llama-3.2-1b-instruct
